### ISSUE TITLE
Criar branchs 9.5 e 9.5 - dev

### ISSUE THREAD

**Issue by verdanatech-luana** [verdanatech/news#1]
![2021-08-16_12-05](https://user-images.githubusercontent.com/86842154/129585735-f528f684-e06a-4419-8a1c-fbd9656b12fb.png)

**Comment by verdanatech-luana** [comment]
Branches criadas.

![2021-08-16_14-11](https://user-images.githubusercontent.com/86842154/129603011-8614ec95-cac9-405a-947e-f5d754f50384.png)

![2021-08-16_14-13](https://user-images.githubusercontent.com/86842154/129603033-0b6e3f8f-969f-4de4-81d6-ed10cedfa35b.png)

**Comment by verdanatech-marcio** [comment]
Testado, funcionando corretamente no GLPI - 9.5.
![TesteNews](https://user-images.githubusercontent.com/80538863/129727911-05891401-1a85-457a-8584-edb848ddbd32.png)
